### ISSUE TITLE
MixPanel causing app to crash on latest react native

### ISSUE THREAD

**Issue by matthewmturner** [mixpanel/mixpanel-react-native#179]
Since upgrading to react native .71 and enabling hermes we have been seeing more crashes and I think they are coming from the native implementation of mixpanel based on the reports we are getting from Sentry. Stack trace included below.  We are on version 2.1.

Is this something that you can fix on your side?

<img width="807" alt="image" src="https://user-images.githubusercontent.com/22136083/226198478-c0233392-f36b-4f37-b1e0-6af5d4c2f56f.png">

**Comment by matthewmturner** [comment]
I've double checked and every instance of this error weve seen was on iOS 16.1+ with React Native .71 (hermes enabled)

**Comment by Allanbcruz** [comment]
I also have the same error, I managed to get the log using adb

<img width="1023" alt="Captura de Tela 2023-03-19 às 19 29 32" src="https://user-images.githubusercontent.com/57270969/226213802-e3a4366b-2f98-4f54-b407-9fcf695b3f6a.png">

**Comment by matthewmturner** [comment]
@Allanbcruz which version of react native are you on?

**Comment by Allanbcruz** [comment]
I migrated today from version:
     "react": "17.0.2",
     "react-native": "0.67.5",
     "mixpanel-react-native": "^2.1.0",
for version:
     "react": "18.2.0",
     "react-native": "0.71.4",
     "mixpanel-react-native": "^2.2.0",

Before it was working normally!

**Comment by matthewmturner** [comment]
Yup same for me only had issues after upgrade.  I was on .65 before though.

**Comment by matthewmturner** [comment]
It's very inconsistent for me though - what about you?  The app still works a good amount of the time it just crashes a lot more than it used to (usually after opening the app).

**Comment by Allanbcruz** [comment]
making a "My bad", sorry @matthewmturner, the error I reported was actually caused by me calling the mixpanel track before it had initialized

**Comment by matthewmturner** [comment]
@Allanbcruz Had you changed anything about your Mixpanel code when upgrading React Native?

**Comment by Allanbcruz** [comment]
No @matthewmturner, due to a failure of the team to manage the releases of our application, there was a coincidence that the faulty code (failed implementation trying to call the mixpanel track before Init()) and the React-Native update version were on the same branch.

**Comment by matthewmturner** [comment]
@Allanbcruz Ah ok, thanks for information!

**Comment by matthewmturner** [comment]
were going to try upgrading to 0.71.4 to see if that helps.  if not we will likely have to disable mixpanel

**Comment by matthewmturner** [comment]
Any feedback from the Mixpanel team please? We updated on our side but it seems likely that the bug is persisting as already saw an instance of it on the version with the fix

**Comment by jaredmixpanel** [comment]
@matthewmturner I'm not able to reproduce the crash and this is the only report we have of such a crash, so I'm not sure what the cause is. But from the screenshot of the stack trace we can see that the crash occurs in `AutomaticProperties.setAutomaticProperties` which can be found here: https://github.com/mixpanel/mixpanel-react-native/blob/master/ios/AutomaticProperties.swift#L7-L9

Which is called from here: https://github.com/mixpanel/mixpanel-react-native/blob/master/ios/MixpanelReactNative.swift#L22

Which receives the `superProperties` object param from your init call: https://github.com/mixpanel/mixpanel-react-native/blob/master/index.js#L65-L67

Are you providing `superProperties` in your init call? If so, what are they and how exactly are you doing it? Let me know if you get any additional information and I'll take a closer look.

**Comment by matthewmturner** [comment]
@jaredmixpanel thanks for the response!  we dont use `superProperties` anywhere.  Below is our core mixpanel code.  Using that we just call `mixpanelInstance.track` throughout the app as needed.

and unfortunately i havent been able to reproduce this in development. im only getting the sentry crash reports in production.

```
import config from 'config';
import { Mixpanel } from 'mixpanel-react-native';

class MixpanelInstance {
  mixpanel: Mixpanel | null;

  isInitialized: boolean;

  constructor() {
    this.mixpanel = null;
    this.isInitialized = false;
  }

  init() {
    try {
      const trackAutomaticEvents = true;
      const mixpanel = new Mixpanel(config.mixpanelToken, trackAutomaticEvents);
      mixpanel.init();
      this.mixpanel = mixpanel;
      this.isInitialized = true;
    } catch (e) {
      console.error(e);
      this.mixpanel = null;
      this.isInitialized = false;
    }
  }

  identify(userId: string) {
    if (!this.isInitialized) return;
    try {
      // We know from the constructor that if isInitialized is true,
      // then mixpanel is not null
      this.mixpanel!.identify(userId);
    } catch (e) {
      console.error(e);
    }
  }

  updateCurrentUser(properties: Object) {
    if (!this.isInitialized) return;
    try {
      // We know from the constructor that if isInitialized is true,
      // then mixpanel is not null
      this.mixpanel!.getPeople().set(properties);
    } catch (e) {
      console.error(e);
    }
  }

  track(name: string, properties: Object) {
    if (!this.isInitialized) return;
    try {
      // We know from the constructor that if isInitialized is true,
      // then mixpanel is not null
      this.mixpanel!.track(name, properties);
    } catch (error) {
      console.error(error);
    }
  }
}

const mixpanelInstance = new MixpanelInstance();

export { mixpanelInstance };
```

**Comment by jaredmixpanel** [comment]
Not sure how this crash is possible then. The stack trace shows AutomaticProperties.swift line 9 being executed: https://github.com/mixpanel/mixpanel-react-native/blob/master/ios/AutomaticProperties.swift#L9

That line is only executed for each key, value pair in that properties dictionary, so if that dictionary is nil... no idea how we could get to that line. As a workaround it may be worth providing an empty object for the `superProperties` param or even some sort of static object like `{"App Name": "VERSD"}`... maybe this will result in a more predictable behavior. In the meantime, I'll add a check to only call `setAutomaticProperties` if `properties` is not nil.

**Comment by jaredmixpanel** [comment]
@matthewmturner Okay, try updating to `v2.2.3` and let me know if that fixed it.

**Comment by matthewmturner** [comment]
@jaredmixpanel will do, thanks much.

**Comment by matthewmturner** [comment]
@jaredmixpanel unfortunately i'm still getting this error even with the update.  Same stack trace.  is there anything else we could try?

**Comment by jaredmixpanel** [comment]
@matthewmturner ok, i've tried something else, let me know if `v2.2.4` fixes it

**Comment by matthewmturner** [comment]
@jaredmixpanel great thanks - will include in our next release and let you know.

**Comment by jaredmixpanel** [comment]
@matthewmturner `v2.2.4` had a bug, sorry about that. please try `v2.2.5` and let me know.

**Comment by matthewmturner** [comment]
@jaredmixpanel updating in our release today, will keep you posted. thanks.

**Comment by matthewmturner** [comment]
@jaredmixpanel FYI were still having this issue

**Comment by matthewmturner** [comment]
Fyi this is report from Crashlytics, a little different.

<img width="1053" alt="image" src="https://github.com/mixpanel/mixpanel-react-native/assets/22136083/646090fc-f1d1-469e-9763-35f67b0821fc">

**Comment by matthewmturner** [comment]
Do you have any ideas for hacks I can do to get around this?

**Comment by matthewmturner** [comment]
@jaredmixpanel from the error seems like it could be related to serverUrl?  But we aren't touching that so not sure why its causing issue

**Comment by matthewmturner** [comment]
@jaredmixpanel do you have any thoughts here?

**Comment by zihejia** [comment]
hi @matthewmturner , I'm reopening this issue for now, I will take a look.

**Comment by matthewmturner** [comment]
@zihejia Thank you!

**Comment by matthewmturner** [comment]
@zihejia hi - just checking in on this.

**Comment by zihejia** [comment]
hi @matthewmturner , please try the latest version v2.3.0, and let me know how it goes.

**Comment by matthewmturner** [comment]
@zihejia we are continuing to have the problem (the error looks a little different though - image attached).  I appreciate that your team has tried putting out several releases to fix this but unless you have a quick fix we are going to stop using mixpanel, its significantly downgrading the quality / experience of using our app.

<img width="753" alt="image" src="https://github.com/mixpanel/mixpanel-react-native/assets/22136083/411633d1-d232-4bc7-9c3a-55678314a6d2">

**Comment by matthewmturner** [comment]
Closing as we no longer use mixpanel

**Comment by TowhidKashem** [comment]
> Closing as we no longer use mixpanel

haha I was just about to comment I am switching to amplitude. I just implemented it and kept getting crashes on production (iOS), in development is works fine. I couldn't even get any errors in sentry cause the app crashes as soon as it's opened. I'm not a native dev so wouldn't even know what to make of the native logs even if I could get em. Screw it the way it's being managed in this thread makes mixpanel looks amateur anyway.

**Comment by catliaw** [comment]
Hi @TowhidKashem (and anyone who is running into this issue), we have recently looked into this issue again but are not able to reproduce the issue. If you are still running into this issue, can you write into support@mixpanel.com citing this Github issue, attach a sample app that gets the errors/crash issue, and the error messages you're getting? You can mention my name in the email, so it will get assigned to me. Thank you very much in advance.

**Comment by gilons** [comment]
We are in 2024, Was still having this issue out of nowhere,  mix panel just started to crash while calling `tracking.init` with values 
```
    environment: __DEV__ ? "development" : "production",
    platform: Platform.OS,
    version: APP_VERSION,
```

Was able to fix it while installing the latest version of the library switching away from native side operations as follows

```
const useNative = false;
const trackAutomaticEvents = true;
const tracking = new Mixpanel(
    "XXXXXXXXXX",
    trackAutomaticEvents,
    useNative,
);
```

**Comment by ThucTrieu** [comment]
Still able to reproduce this error on latest version (3.1.2), react-native: 0.79.5. Should reopen this issue :) 
This bug only occurs in production, not in dev

**Comment by ThucTrieu** [comment]
Hi @zihejia Any updates for this issue? We shouldn't close that because `Closing as we no longer use mixpanel`
